ktor:
  application:
    modules:
      - owlstilttherheads.com.ApplicationKt.module
  deployment:
    port: "$PORT:8080"

db:
  jdbcUrl: "$JDBC_URL:jdbc:postgresql://localhost:5432/postgres"
  userName: "$DB_USER_NAME:user"
